title: Ophelia Sin # your name (or website title) here
logo: "/images/royce_grad_headshot.png?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I'm currently a second year master student at North Carolina State University studying Computer Science. Previously, I graduated from UCLA with a double major in Communication and Geography.

  <br><br>
  Find me on <a href="https://www.linkedin.com/in/opheliasin/">LinkedIn</a> !<br><br>
  
theme: jekyll-theme-minimal
google_analytics: G-573G3WM05T # your Google Analytics tracking ID here
