title: Ophelia Sin # your name (or website title) here
logo: "/images/headshot.png?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I'm a 4th year undergrdaute double majoring in Communication and Geography at UCLA. 
  <br><br>
  I'm currently a research assistant at the <a href = "https://mobility-lab.seas.ucla.edu/">UCLA Mobility Lab </a>.
  <br><br>
  Find me on <a href="https://www.linkedin.com/in/opheliasin/">LinkedIn</a> !<br><br>
  
theme: jekyll-theme-minimal
google_analytics: G-573G3WM05T # your Google Analytics tracking ID here
